### PR TITLE
Add missing Date model

### PR DESCRIPTION
**Pull request by jonathaningram**
Add Primitive field so that primitive models don't render.

Also add panic if trying to access a model that doesn't exist.

### CODE REVIEW

**Comment by jonathaningram** [comment]
@larrymyers btw here's a PB file that shows the original error where the generator tried to access a model in the map that doesn't exist. P.S. we need to get these kinds of proto files in the repo and tested I suppose.

```proto
syntax = "proto3";
package clients;

import "google/protobuf/timestamp.proto";

service Clients {
  rpc GetClients(Empty) returns (GetClientsResponse);
}

message Empty {}

message GetClientsResponse {
  repeated Client clients = 1;
}

message Client {
  string id = 1;
  google.protobuf.Timestamp created_time = 2;
  google.protobuf.Timestamp updated_time = 3;
  string email = 4;
  string name = 5;
}
```

**Comment by larrymyers** [comment]
@jonathaningram I'm likely just having a slow morning, but what's the issue here? Is the generator barfing on the WKT Timestamp?  There are already conditional checks in there to handle google's WKT Timestamp.

**Comment by jonathaningram** [comment]
@larrymyers when finding the TS type, if the field is a `google.protobuf.Timestamp`, then the TS type returned will be `Date` (https://github.com/larrymyers/protoc-gen-twirp_typescript/blob/master/generator/client.go#L309)

Sure, you have a guard in this for loop to stop proceeding if the field type is `Date` (https://github.com/larrymyers/protoc-gen-twirp_typescript/blob/master/generator/client.go#L138)

But you don't have the guard in the subsequent recursive for loops called https://github.com/larrymyers/protoc-gen-twirp_typescript/blob/master/generator/client.go#L148 and https://github.com/larrymyers/protoc-gen-twirp_typescript/blob/master/generator/client.go#L152

Note that in the protobuf example in my previous comment, this shows the error because of the nested messages:

```
message GetClientsResponse
  message Client
    google.protobuf.Timestamp (_model actually becomes a "Date" hence the nil map entry error_) created_time
```

**Comment by larrymyers** [comment]
👍

**Pull request merged**
